// This file is @generated by prost-build.
#[derive(serde::Serialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GatewayEvent {
    #[prost(oneof = "gateway_event::Event", tags = "1")]
    pub event: ::core::option::Option<gateway_event::Event>,
}
/// Nested message and enum types in `GatewayEvent`.
pub mod gateway_event {
    #[derive(serde::Serialize)]
    #[derive(Clone, Copy, PartialEq, ::prost::Oneof)]
    pub enum Event {
        #[prost(message, tag = "1")]
        Ping(super::PingEvent),
    }
}
#[derive(serde::Serialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct PingEvent {
    #[prost(uint32, tag = "3")]
    pub cpu: u32,
    #[prost(uint32, tag = "4")]
    pub memory: u32,
    #[prost(uint32, tag = "5")]
    pub disk: u32,
    #[prost(message, optional, tag = "6")]
    pub webrtc: ::core::option::Option<ping_event::ServiceStats>,
    #[prost(message, optional, tag = "7")]
    pub rtpengine: ::core::option::Option<ping_event::ServiceStats>,
    #[prost(oneof = "ping_event::Origin", tags = "1, 2")]
    pub origin: ::core::option::Option<ping_event::Origin>,
}
/// Nested message and enum types in `PingEvent`.
pub mod ping_event {
    #[derive(serde::Serialize)]
    #[derive(Clone, Copy, PartialEq, ::prost::Message)]
    pub struct MediaOrigin {}
    #[derive(serde::Serialize)]
    #[derive(Clone, Copy, PartialEq, ::prost::Message)]
    pub struct GatewayOrigin {
        #[prost(uint32, tag = "1")]
        pub zone: u32,
        #[prost(message, optional, tag = "3")]
        pub location: ::core::option::Option<gateway_origin::Location>,
    }
    /// Nested message and enum types in `GatewayOrigin`.
    pub mod gateway_origin {
        #[derive(serde::Serialize)]
        #[derive(Clone, Copy, PartialEq, ::prost::Message)]
        pub struct Location {
            #[prost(float, tag = "1")]
            pub lat: f32,
            #[prost(float, tag = "2")]
            pub lon: f32,
        }
    }
    #[derive(serde::Serialize)]
    #[derive(Clone, Copy, PartialEq, ::prost::Message)]
    pub struct ServiceStats {
        #[prost(uint32, tag = "1")]
        pub live: u32,
        #[prost(uint32, tag = "2")]
        pub max: u32,
        #[prost(bool, tag = "3")]
        pub active: bool,
    }
    #[derive(serde::Serialize)]
    #[derive(Clone, Copy, PartialEq, ::prost::Oneof)]
    pub enum Origin {
        #[prost(message, tag = "1")]
        Media(MediaOrigin),
        #[prost(message, tag = "2")]
        Gateway(GatewayOrigin),
    }
}
