// This file is @generated by prost-build.
#[derive(serde::Serialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HookEvent {
    #[prost(uint32, tag = "1")]
    pub node: u32,
    #[prost(uint64, tag = "2")]
    pub ts: u64,
    #[prost(oneof = "hook_event::Event", tags = "3, 4, 5, 6")]
    pub event: ::core::option::Option<hook_event::Event>,
}
/// Nested message and enum types in `HookEvent`.
pub mod hook_event {
    #[derive(serde::Serialize)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Event {
        #[prost(message, tag = "3")]
        Room(super::RoomEvent),
        #[prost(message, tag = "4")]
        Peer(super::PeerEvent),
        #[prost(message, tag = "5")]
        Record(super::RecordEvent),
        #[prost(message, tag = "6")]
        Compose(super::ComposeEvent),
    }
}
#[derive(serde::Serialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConnectorRequest {
    #[prost(uint64, tag = "1")]
    pub req_id: u64,
    #[prost(uint64, tag = "2")]
    pub ts: u64,
    #[prost(oneof = "connector_request::Request", tags = "3, 4")]
    pub request: ::core::option::Option<connector_request::Request>,
}
/// Nested message and enum types in `ConnectorRequest`.
pub mod connector_request {
    #[derive(serde::Serialize)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Request {
        #[prost(message, tag = "3")]
        Peer(super::PeerEvent),
        #[prost(message, tag = "4")]
        Record(super::RecordReq),
    }
}
#[derive(serde::Serialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConnectorResponse {
    #[prost(uint64, tag = "1")]
    pub req_id: u64,
    #[prost(oneof = "connector_response::Response", tags = "2, 3, 4")]
    pub response: ::core::option::Option<connector_response::Response>,
}
/// Nested message and enum types in `ConnectorResponse`.
pub mod connector_response {
    #[derive(serde::Serialize)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct Error {
        #[prost(uint32, tag = "1")]
        pub code: u32,
        #[prost(string, tag = "2")]
        pub message: ::prost::alloc::string::String,
    }
    #[derive(serde::Serialize)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Response {
        #[prost(message, tag = "2")]
        Error(Error),
        #[prost(message, tag = "3")]
        Peer(super::PeerRes),
        #[prost(message, tag = "4")]
        Record(super::RecordRes),
    }
}
#[derive(serde::Serialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PeerEvent {
    #[prost(string, tag = "19")]
    pub app: ::prost::alloc::string::String,
    #[prost(uint64, tag = "1")]
    pub session_id: u64,
    #[prost(
        oneof = "peer_event::Event",
        tags = "2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18"
    )]
    pub event: ::core::option::Option<peer_event::Event>,
}
/// Nested message and enum types in `PeerEvent`.
pub mod peer_event {
    #[derive(serde::Serialize)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct RouteBegin {
        #[prost(string, tag = "1")]
        pub remote_ip: ::prost::alloc::string::String,
    }
    #[derive(serde::Serialize)]
    #[derive(Clone, Copy, PartialEq, ::prost::Message)]
    pub struct RouteSuccess {
        #[prost(uint32, tag = "1")]
        pub after_ms: u32,
        #[prost(uint32, tag = "2")]
        pub dest_node: u32,
    }
    #[derive(serde::Serialize)]
    #[derive(Clone, Copy, PartialEq, ::prost::Message)]
    pub struct RouteError {
        #[prost(uint32, tag = "1")]
        pub after_ms: u32,
        #[prost(uint32, optional, tag = "2")]
        pub dest_node: ::core::option::Option<u32>,
        #[prost(enumeration = "route_error::ErrorType", tag = "3")]
        pub error: i32,
    }
    /// Nested message and enum types in `RouteError`.
    pub mod route_error {
        #[derive(serde::Serialize)]
        #[derive(
            Clone,
            Copy,
            Debug,
            PartialEq,
            Eq,
            Hash,
            PartialOrd,
            Ord,
            ::prost::Enumeration
        )]
        #[repr(i32)]
        pub enum ErrorType {
            PoolEmpty = 0,
            Timeout = 1,
            GatewayError = 2,
            MediaError = 3,
        }
        impl ErrorType {
            /// String value of the enum field names used in the ProtoBuf definition.
            ///
            /// The values are not transformed in any way and thus are considered stable
            /// (if the ProtoBuf definition does not change) and safe for programmatic use.
            pub fn as_str_name(&self) -> &'static str {
                match self {
                    Self::PoolEmpty => "PoolEmpty",
                    Self::Timeout => "Timeout",
                    Self::GatewayError => "GatewayError",
                    Self::MediaError => "MediaError",
                }
            }
            /// Creates an enum from field names used in the ProtoBuf definition.
            pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
                match value {
                    "PoolEmpty" => Some(Self::PoolEmpty),
                    "Timeout" => Some(Self::Timeout),
                    "GatewayError" => Some(Self::GatewayError),
                    "MediaError" => Some(Self::MediaError),
                    _ => None,
                }
            }
        }
    }
    #[derive(serde::Serialize)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct Connecting {
        #[prost(string, tag = "1")]
        pub remote_ip: ::prost::alloc::string::String,
    }
    #[derive(serde::Serialize)]
    #[derive(Clone, Copy, PartialEq, ::prost::Message)]
    pub struct ConnectError {
        #[prost(uint32, tag = "1")]
        pub after_ms: u32,
        #[prost(enumeration = "connect_error::ErrorType", tag = "2")]
        pub error: i32,
    }
    /// Nested message and enum types in `ConnectError`.
    pub mod connect_error {
        #[derive(serde::Serialize)]
        #[derive(
            Clone,
            Copy,
            Debug,
            PartialEq,
            Eq,
            Hash,
            PartialOrd,
            Ord,
            ::prost::Enumeration
        )]
        #[repr(i32)]
        pub enum ErrorType {
            InvalidSdp = 0,
            Timeout = 1,
        }
        impl ErrorType {
            /// String value of the enum field names used in the ProtoBuf definition.
            ///
            /// The values are not transformed in any way and thus are considered stable
            /// (if the ProtoBuf definition does not change) and safe for programmatic use.
            pub fn as_str_name(&self) -> &'static str {
                match self {
                    Self::InvalidSdp => "InvalidSdp",
                    Self::Timeout => "Timeout",
                }
            }
            /// Creates an enum from field names used in the ProtoBuf definition.
            pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
                match value {
                    "InvalidSdp" => Some(Self::InvalidSdp),
                    "Timeout" => Some(Self::Timeout),
                    _ => None,
                }
            }
        }
    }
    #[derive(serde::Serialize)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct Join {
        #[prost(string, tag = "1")]
        pub room: ::prost::alloc::string::String,
        #[prost(string, tag = "2")]
        pub peer: ::prost::alloc::string::String,
    }
    #[derive(serde::Serialize)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct Leave {
        #[prost(string, tag = "1")]
        pub room: ::prost::alloc::string::String,
        #[prost(string, tag = "2")]
        pub peer: ::prost::alloc::string::String,
    }
    #[derive(serde::Serialize)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct Connected {
        #[prost(uint32, tag = "1")]
        pub after_ms: u32,
        #[prost(string, tag = "2")]
        pub remote_ip: ::prost::alloc::string::String,
    }
    #[derive(serde::Serialize)]
    #[derive(Clone, Copy, PartialEq, ::prost::Message)]
    pub struct Stats {
        #[prost(uint64, tag = "1")]
        pub sent_bytes: u64,
        #[prost(uint64, tag = "2")]
        pub received_bytes: u64,
    }
    #[derive(serde::Serialize)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct Reconnecting {
        #[prost(string, tag = "1")]
        pub remote_ip: ::prost::alloc::string::String,
    }
    #[derive(serde::Serialize)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct Reconnected {
        #[prost(uint32, tag = "1")]
        pub after_ms: u32,
        #[prost(string, tag = "2")]
        pub remote_ip: ::prost::alloc::string::String,
    }
    #[derive(serde::Serialize)]
    #[derive(Clone, Copy, PartialEq, ::prost::Message)]
    pub struct Disconnected {
        #[prost(uint32, tag = "1")]
        pub duration_ms: u32,
        #[prost(enumeration = "disconnected::Reason", tag = "2")]
        pub reason: i32,
    }
    /// Nested message and enum types in `Disconnected`.
    pub mod disconnected {
        #[derive(serde::Serialize)]
        #[derive(
            Clone,
            Copy,
            Debug,
            PartialEq,
            Eq,
            Hash,
            PartialOrd,
            Ord,
            ::prost::Enumeration
        )]
        #[repr(i32)]
        pub enum Reason {
            UserAction = 0,
            Timeout = 1,
            NodeShutdown = 2,
            KickByApi = 3,
        }
        impl Reason {
            /// String value of the enum field names used in the ProtoBuf definition.
            ///
            /// The values are not transformed in any way and thus are considered stable
            /// (if the ProtoBuf definition does not change) and safe for programmatic use.
            pub fn as_str_name(&self) -> &'static str {
                match self {
                    Self::UserAction => "UserAction",
                    Self::Timeout => "Timeout",
                    Self::NodeShutdown => "NodeShutdown",
                    Self::KickByApi => "KickByAPI",
                }
            }
            /// Creates an enum from field names used in the ProtoBuf definition.
            pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
                match value {
                    "UserAction" => Some(Self::UserAction),
                    "Timeout" => Some(Self::Timeout),
                    "NodeShutdown" => Some(Self::NodeShutdown),
                    "KickByAPI" => Some(Self::KickByApi),
                    _ => None,
                }
            }
        }
    }
    #[derive(serde::Serialize)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct RemoteTrackStarted {
        #[prost(string, tag = "1")]
        pub track: ::prost::alloc::string::String,
        #[prost(enumeration = "super::super::shared::Kind", tag = "2")]
        pub kind: i32,
    }
    #[derive(serde::Serialize)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct RemoteTrackEnded {
        #[prost(string, tag = "1")]
        pub track: ::prost::alloc::string::String,
        #[prost(enumeration = "super::super::shared::Kind", tag = "2")]
        pub kind: i32,
    }
    #[derive(serde::Serialize)]
    #[derive(Clone, Copy, PartialEq, ::prost::Message)]
    pub struct LocalTrack {
        #[prost(int32, tag = "1")]
        pub track: i32,
        #[prost(enumeration = "super::super::shared::Kind", tag = "2")]
        pub kind: i32,
    }
    #[derive(serde::Serialize)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct LocalTrackAttach {
        #[prost(int32, tag = "1")]
        pub track: i32,
        #[prost(string, tag = "2")]
        pub remote_peer: ::prost::alloc::string::String,
        #[prost(string, tag = "3")]
        pub remote_track: ::prost::alloc::string::String,
    }
    #[derive(serde::Serialize)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct LocalTrackDetach {
        #[prost(int32, tag = "1")]
        pub track: i32,
        #[prost(string, tag = "2")]
        pub remote_peer: ::prost::alloc::string::String,
        #[prost(string, tag = "3")]
        pub remote_track: ::prost::alloc::string::String,
    }
    #[derive(serde::Serialize)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Event {
        #[prost(message, tag = "2")]
        RouteBegin(RouteBegin),
        #[prost(message, tag = "3")]
        RouteSuccess(RouteSuccess),
        #[prost(message, tag = "4")]
        RouteError(RouteError),
        #[prost(message, tag = "5")]
        Connecting(Connecting),
        #[prost(message, tag = "6")]
        Connected(Connected),
        #[prost(message, tag = "7")]
        ConnectError(ConnectError),
        #[prost(message, tag = "8")]
        Stats(Stats),
        #[prost(message, tag = "9")]
        Reconnect(Reconnecting),
        #[prost(message, tag = "10")]
        Reconnected(Reconnected),
        #[prost(message, tag = "11")]
        Disconnected(Disconnected),
        #[prost(message, tag = "12")]
        Join(Join),
        #[prost(message, tag = "13")]
        Leave(Leave),
        #[prost(message, tag = "14")]
        RemoteTrackStarted(RemoteTrackStarted),
        #[prost(message, tag = "15")]
        RemoteTrackEnded(RemoteTrackEnded),
        #[prost(message, tag = "16")]
        LocalTrack(LocalTrack),
        #[prost(message, tag = "17")]
        LocalTrackAttach(LocalTrackAttach),
        #[prost(message, tag = "18")]
        LocalTrackDetach(LocalTrackDetach),
    }
}
#[derive(serde::Serialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct PeerRes {}
#[derive(serde::Serialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RoomEvent {
    #[prost(string, tag = "7")]
    pub app: ::prost::alloc::string::String,
    #[prost(string, tag = "1")]
    pub room: ::prost::alloc::string::String,
    #[prost(oneof = "room_event::Event", tags = "2, 3, 4, 5, 6")]
    pub event: ::core::option::Option<room_event::Event>,
}
/// Nested message and enum types in `RoomEvent`.
pub mod room_event {
    #[derive(serde::Serialize)]
    #[derive(Clone, Copy, PartialEq, ::prost::Message)]
    pub struct RoomStarted {}
    #[derive(serde::Serialize)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct RoomPeerJoined {
        #[prost(string, tag = "1")]
        pub peer: ::prost::alloc::string::String,
    }
    #[derive(serde::Serialize)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct RoomPeerLeaved {
        #[prost(string, tag = "1")]
        pub peer: ::prost::alloc::string::String,
    }
    #[derive(serde::Serialize)]
    #[derive(Clone, Copy, PartialEq, ::prost::Message)]
    pub struct RoomAllPeersLeaved {}
    #[derive(serde::Serialize)]
    #[derive(Clone, Copy, PartialEq, ::prost::Message)]
    pub struct RoomStopped {}
    #[derive(serde::Serialize)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Event {
        #[prost(message, tag = "2")]
        Started(RoomStarted),
        #[prost(message, tag = "3")]
        PeerJoined(RoomPeerJoined),
        #[prost(message, tag = "4")]
        PeerLeaved(RoomPeerLeaved),
        #[prost(message, tag = "5")]
        AllPeersLeaved(RoomAllPeersLeaved),
        #[prost(message, tag = "6")]
        Stopped(RoomStopped),
    }
}
#[derive(serde::Serialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RecordEvent {
    #[prost(string, tag = "4")]
    pub app: ::prost::alloc::string::String,
    #[prost(string, tag = "1")]
    pub room: ::prost::alloc::string::String,
    #[prost(oneof = "record_event::Event", tags = "2, 3")]
    pub event: ::core::option::Option<record_event::Event>,
}
/// Nested message and enum types in `RecordEvent`.
pub mod record_event {
    #[derive(serde::Serialize)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct RecordStarted {
        #[prost(string, tag = "1")]
        pub path: ::prost::alloc::string::String,
    }
    #[derive(serde::Serialize)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct RecordPeerJoined {
        #[prost(string, tag = "1")]
        pub peer: ::prost::alloc::string::String,
        #[prost(string, tag = "2")]
        pub path: ::prost::alloc::string::String,
    }
    #[derive(serde::Serialize)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Event {
        #[prost(message, tag = "2")]
        Started(RecordStarted),
        #[prost(message, tag = "3")]
        PeerJoined(RecordPeerJoined),
    }
}
#[derive(serde::Serialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ComposeEvent {
    #[prost(string, tag = "1")]
    pub app: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub job_id: ::prost::alloc::string::String,
    #[prost(oneof = "compose_event::Event", tags = "10, 11, 12")]
    pub event: ::core::option::Option<compose_event::Event>,
}
/// Nested message and enum types in `ComposeEvent`.
pub mod compose_event {
    #[derive(serde::Serialize)]
    #[derive(Clone, Copy, PartialEq, ::prost::Message)]
    pub struct RecordJobStarted {}
    #[derive(serde::Serialize)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct RecordJobFailed {
        #[prost(string, tag = "2")]
        pub error: ::prost::alloc::string::String,
    }
    #[derive(serde::Serialize)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct RecordJobCompleted {
        #[prost(message, optional, tag = "1")]
        pub transmux: ::core::option::Option<record_job_completed::TransmuxSummary>,
        #[prost(message, optional, tag = "2")]
        pub compose: ::core::option::Option<record_job_completed::ComposeSummary>,
    }
    /// Nested message and enum types in `RecordJobCompleted`.
    pub mod record_job_completed {
        #[derive(serde::Serialize)]
        #[derive(Clone, PartialEq, ::prost::Message)]
        pub struct TrackTimeline {
            #[prost(string, tag = "1")]
            pub path: ::prost::alloc::string::String,
            #[prost(uint64, tag = "2")]
            pub start: u64,
            /// Optional field, can be omitted
            #[prost(uint64, tag = "3")]
            pub end: u64,
        }
        #[derive(serde::Serialize)]
        #[derive(Clone, PartialEq, ::prost::Message)]
        pub struct TrackSummary {
            #[prost(enumeration = "super::super::super::shared::Kind", tag = "1")]
            pub kind: i32,
            #[prost(message, repeated, tag = "2")]
            pub timeline: ::prost::alloc::vec::Vec<TrackTimeline>,
        }
        #[derive(serde::Serialize)]
        #[derive(Clone, PartialEq, ::prost::Message)]
        pub struct SessionSummary {
            #[prost(map = "string, message", tag = "1")]
            pub track: ::std::collections::HashMap<
                ::prost::alloc::string::String,
                TrackSummary,
            >,
        }
        #[derive(serde::Serialize)]
        #[derive(Clone, PartialEq, ::prost::Message)]
        pub struct PeerSummary {
            #[prost(map = "uint64, message", tag = "1")]
            pub sessions: ::std::collections::HashMap<u64, SessionSummary>,
        }
        #[derive(serde::Serialize)]
        #[derive(Clone, PartialEq, ::prost::Message)]
        pub struct TransmuxSummary {
            #[prost(string, tag = "1")]
            pub metadata_json: ::prost::alloc::string::String,
            #[prost(map = "string, message", tag = "2")]
            pub peers: ::std::collections::HashMap<
                ::prost::alloc::string::String,
                PeerSummary,
            >,
        }
        #[derive(serde::Serialize)]
        #[derive(Clone, PartialEq, ::prost::Message)]
        pub struct ComposeSummary {
            #[prost(string, tag = "1")]
            pub media_uri: ::prost::alloc::string::String,
            #[prost(uint64, tag = "2")]
            pub duration_ms: u64,
        }
    }
    #[derive(serde::Serialize)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Event {
        #[prost(message, tag = "10")]
        Started(RecordJobStarted),
        #[prost(message, tag = "11")]
        Failed(RecordJobFailed),
        #[prost(message, tag = "12")]
        Completed(RecordJobCompleted),
    }
}
#[derive(serde::Serialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RecordReq {
    #[prost(string, tag = "1")]
    pub room: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub peer: ::prost::alloc::string::String,
    #[prost(uint64, tag = "3")]
    pub session: u64,
    #[prost(uint32, tag = "4")]
    pub index: u32,
    #[prost(uint64, tag = "5")]
    pub from_ts: u64,
    #[prost(uint64, tag = "6")]
    pub to_ts: u64,
    #[prost(string, tag = "7")]
    pub app: ::prost::alloc::string::String,
}
#[derive(serde::Serialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RecordRes {
    #[prost(string, tag = "1")]
    pub s3_uri: ::prost::alloc::string::String,
}
#[derive(serde::Serialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetParams {
    #[prost(uint32, tag = "1")]
    pub page: u32,
    #[prost(uint32, tag = "2")]
    pub limit: u32,
}
#[derive(serde::Serialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetRooms {
    #[prost(message, repeated, tag = "1")]
    pub rooms: ::prost::alloc::vec::Vec<get_rooms::RoomInfo>,
    #[prost(message, optional, tag = "2")]
    pub pagination: ::core::option::Option<super::shared::Pagination>,
}
/// Nested message and enum types in `GetRooms`.
pub mod get_rooms {
    #[derive(serde::Serialize)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct RoomInfo {
        #[prost(int32, tag = "1")]
        pub id: i32,
        #[prost(string, tag = "5")]
        pub app: ::prost::alloc::string::String,
        #[prost(string, tag = "2")]
        pub room: ::prost::alloc::string::String,
        #[prost(uint64, tag = "3")]
        pub created_at: u64,
        #[prost(uint32, tag = "4")]
        pub peers: u32,
        #[prost(string, optional, tag = "6")]
        pub record: ::core::option::Option<::prost::alloc::string::String>,
    }
}
#[derive(serde::Serialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetPeerParams {
    #[prost(int32, optional, tag = "1")]
    pub room: ::core::option::Option<i32>,
    #[prost(uint32, tag = "2")]
    pub page: u32,
    #[prost(uint32, tag = "3")]
    pub limit: u32,
}
#[derive(serde::Serialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PeerSession {
    #[prost(int32, tag = "1")]
    pub id: i32,
    #[prost(int32, tag = "2")]
    pub peer_id: i32,
    #[prost(string, tag = "3")]
    pub peer: ::prost::alloc::string::String,
    #[prost(uint64, tag = "4")]
    pub session: u64,
    #[prost(uint64, tag = "5")]
    pub created_at: u64,
    #[prost(uint64, tag = "6")]
    pub joined_at: u64,
    #[prost(uint64, optional, tag = "7")]
    pub leaved_at: ::core::option::Option<u64>,
}
#[derive(serde::Serialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetPeers {
    #[prost(message, repeated, tag = "1")]
    pub peers: ::prost::alloc::vec::Vec<get_peers::PeerInfo>,
    #[prost(message, optional, tag = "2")]
    pub pagination: ::core::option::Option<super::shared::Pagination>,
}
/// Nested message and enum types in `GetPeers`.
pub mod get_peers {
    #[derive(serde::Serialize)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct PeerInfo {
        #[prost(int32, tag = "1")]
        pub id: i32,
        #[prost(int32, tag = "2")]
        pub room_id: i32,
        #[prost(string, tag = "3")]
        pub room: ::prost::alloc::string::String,
        #[prost(string, tag = "4")]
        pub peer: ::prost::alloc::string::String,
        #[prost(uint64, tag = "5")]
        pub created_at: u64,
        #[prost(message, repeated, tag = "6")]
        pub sessions: ::prost::alloc::vec::Vec<super::PeerSession>,
    }
}
#[derive(serde::Serialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetSessions {
    #[prost(message, repeated, tag = "1")]
    pub sessions: ::prost::alloc::vec::Vec<get_sessions::SessionInfo>,
    #[prost(message, optional, tag = "2")]
    pub pagination: ::core::option::Option<super::shared::Pagination>,
}
/// Nested message and enum types in `GetSessions`.
pub mod get_sessions {
    #[derive(serde::Serialize)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct SessionInfo {
        #[prost(string, tag = "7")]
        pub app: ::prost::alloc::string::String,
        #[prost(uint64, tag = "1")]
        pub id: u64,
        #[prost(string, optional, tag = "2")]
        pub ip: ::core::option::Option<::prost::alloc::string::String>,
        #[prost(string, optional, tag = "3")]
        pub user_agent: ::core::option::Option<::prost::alloc::string::String>,
        #[prost(string, optional, tag = "4")]
        pub sdk: ::core::option::Option<::prost::alloc::string::String>,
        #[prost(uint64, tag = "5")]
        pub created_at: u64,
        #[prost(message, repeated, tag = "6")]
        pub peers: ::prost::alloc::vec::Vec<super::PeerSession>,
    }
}
#[derive(serde::Serialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetEventParams {
    #[prost(uint64, optional, tag = "1")]
    pub session: ::core::option::Option<u64>,
    #[prost(uint64, optional, tag = "2")]
    pub start_ts: ::core::option::Option<u64>,
    #[prost(uint64, optional, tag = "3")]
    pub end_ts: ::core::option::Option<u64>,
    #[prost(uint32, tag = "4")]
    pub page: u32,
    #[prost(uint32, tag = "5")]
    pub limit: u32,
}
#[derive(serde::Serialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetEvents {
    #[prost(message, repeated, tag = "1")]
    pub events: ::prost::alloc::vec::Vec<get_events::EventInfo>,
    #[prost(message, optional, tag = "2")]
    pub pagination: ::core::option::Option<super::shared::Pagination>,
}
/// Nested message and enum types in `GetEvents`.
pub mod get_events {
    #[derive(serde::Serialize)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct EventInfo {
        #[prost(int32, tag = "1")]
        pub id: i32,
        #[prost(uint32, tag = "2")]
        pub node: u32,
        #[prost(uint64, tag = "3")]
        pub node_ts: u64,
        #[prost(uint64, tag = "4")]
        pub session: u64,
        #[prost(uint64, tag = "5")]
        pub created_at: u64,
        #[prost(string, tag = "6")]
        pub event: ::prost::alloc::string::String,
        #[prost(string, optional, tag = "7")]
        pub meta: ::core::option::Option<::prost::alloc::string::String>,
    }
}
/// Generated client implementations.
pub mod media_connector_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct MediaConnectorClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl MediaConnectorClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> MediaConnectorClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> MediaConnectorClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            MediaConnectorClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn rooms(
            &mut self,
            request: impl tonic::IntoRequest<super::GetParams>,
        ) -> std::result::Result<tonic::Response<super::GetRooms>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cluster_connector.MediaConnector/Rooms",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("cluster_connector.MediaConnector", "Rooms"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn peers(
            &mut self,
            request: impl tonic::IntoRequest<super::GetPeerParams>,
        ) -> std::result::Result<tonic::Response<super::GetPeers>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cluster_connector.MediaConnector/Peers",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("cluster_connector.MediaConnector", "Peers"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn sessions(
            &mut self,
            request: impl tonic::IntoRequest<super::GetParams>,
        ) -> std::result::Result<tonic::Response<super::GetSessions>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cluster_connector.MediaConnector/Sessions",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("cluster_connector.MediaConnector", "Sessions"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn events(
            &mut self,
            request: impl tonic::IntoRequest<super::GetEventParams>,
        ) -> std::result::Result<tonic::Response<super::GetEvents>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cluster_connector.MediaConnector/Events",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("cluster_connector.MediaConnector", "Events"));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod media_connector_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with MediaConnectorServer.
    #[async_trait]
    pub trait MediaConnector: std::marker::Send + std::marker::Sync + 'static {
        async fn rooms(
            &self,
            request: tonic::Request<super::GetParams>,
        ) -> std::result::Result<tonic::Response<super::GetRooms>, tonic::Status>;
        async fn peers(
            &self,
            request: tonic::Request<super::GetPeerParams>,
        ) -> std::result::Result<tonic::Response<super::GetPeers>, tonic::Status>;
        async fn sessions(
            &self,
            request: tonic::Request<super::GetParams>,
        ) -> std::result::Result<tonic::Response<super::GetSessions>, tonic::Status>;
        async fn events(
            &self,
            request: tonic::Request<super::GetEventParams>,
        ) -> std::result::Result<tonic::Response<super::GetEvents>, tonic::Status>;
    }
    #[derive(Debug)]
    pub struct MediaConnectorServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> MediaConnectorServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for MediaConnectorServer<T>
    where
        T: MediaConnector,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/cluster_connector.MediaConnector/Rooms" => {
                    #[allow(non_camel_case_types)]
                    struct RoomsSvc<T: MediaConnector>(pub Arc<T>);
                    impl<T: MediaConnector> tonic::server::UnaryService<super::GetParams>
                    for RoomsSvc<T> {
                        type Response = super::GetRooms;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetParams>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MediaConnector>::rooms(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = RoomsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/cluster_connector.MediaConnector/Peers" => {
                    #[allow(non_camel_case_types)]
                    struct PeersSvc<T: MediaConnector>(pub Arc<T>);
                    impl<
                        T: MediaConnector,
                    > tonic::server::UnaryService<super::GetPeerParams> for PeersSvc<T> {
                        type Response = super::GetPeers;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetPeerParams>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MediaConnector>::peers(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = PeersSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/cluster_connector.MediaConnector/Sessions" => {
                    #[allow(non_camel_case_types)]
                    struct SessionsSvc<T: MediaConnector>(pub Arc<T>);
                    impl<T: MediaConnector> tonic::server::UnaryService<super::GetParams>
                    for SessionsSvc<T> {
                        type Response = super::GetSessions;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetParams>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MediaConnector>::sessions(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = SessionsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/cluster_connector.MediaConnector/Events" => {
                    #[allow(non_camel_case_types)]
                    struct EventsSvc<T: MediaConnector>(pub Arc<T>);
                    impl<
                        T: MediaConnector,
                    > tonic::server::UnaryService<super::GetEventParams>
                    for EventsSvc<T> {
                        type Response = super::GetEvents;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetEventParams>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MediaConnector>::events(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = EventsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(empty_body());
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for MediaConnectorServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "cluster_connector.MediaConnector";
    impl<T> tonic::server::NamedService for MediaConnectorServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
