// This file is @generated by prost-build.
#[derive(serde::Serialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Empty {}
/// For whip
#[derive(serde::Serialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WhipConnectRequest {
    #[prost(string, tag = "1")]
    pub user_agent: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub ip: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub sdp: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub room: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub peer: ::prost::alloc::string::String,
    #[prost(uint64, tag = "6")]
    pub session_id: u64,
    #[prost(bool, tag = "7")]
    pub record: bool,
    #[prost(string, optional, tag = "8")]
    pub extra_data: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(message, optional, tag = "9")]
    pub app: ::core::option::Option<super::shared::AppContext>,
}
#[derive(serde::Serialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WhipConnectResponse {
    #[prost(string, tag = "1")]
    pub conn: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub sdp: ::prost::alloc::string::String,
}
#[derive(serde::Serialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WhipRemoteIceRequest {
    #[prost(string, tag = "1")]
    pub conn: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub ice: ::prost::alloc::string::String,
}
#[derive(serde::Serialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WhipRemoteIceResponse {
    #[prost(string, tag = "1")]
    pub conn: ::prost::alloc::string::String,
}
#[derive(serde::Serialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WhipCloseRequest {
    #[prost(string, tag = "1")]
    pub conn: ::prost::alloc::string::String,
}
#[derive(serde::Serialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WhipCloseResponse {
    #[prost(string, tag = "1")]
    pub conn: ::prost::alloc::string::String,
}
/// For whep
#[derive(serde::Serialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WhepConnectRequest {
    #[prost(string, tag = "1")]
    pub user_agent: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub ip: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub sdp: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub room: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub peer: ::prost::alloc::string::String,
    #[prost(uint64, tag = "6")]
    pub session_id: u64,
    #[prost(string, optional, tag = "8")]
    pub extra_data: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(message, optional, tag = "9")]
    pub app: ::core::option::Option<super::shared::AppContext>,
}
#[derive(serde::Serialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WhepConnectResponse {
    #[prost(string, tag = "1")]
    pub conn: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub sdp: ::prost::alloc::string::String,
}
#[derive(serde::Serialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WhepRemoteIceRequest {
    #[prost(string, tag = "1")]
    pub conn: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub ice: ::prost::alloc::string::String,
}
#[derive(serde::Serialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WhepRemoteIceResponse {
    #[prost(string, tag = "1")]
    pub conn: ::prost::alloc::string::String,
}
#[derive(serde::Serialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WhepCloseRequest {
    #[prost(string, tag = "1")]
    pub conn: ::prost::alloc::string::String,
}
#[derive(serde::Serialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WhepCloseResponse {
    #[prost(string, tag = "1")]
    pub conn: ::prost::alloc::string::String,
}
/// For SDK
#[derive(serde::Serialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WebrtcConnectRequest {
    #[prost(string, tag = "1")]
    pub user_agent: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub ip: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub req: ::core::option::Option<super::gateway::ConnectRequest>,
    #[prost(uint64, tag = "4")]
    pub session_id: u64,
    #[prost(bool, tag = "5")]
    pub record: bool,
    #[prost(string, optional, tag = "8")]
    pub extra_data: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(message, optional, tag = "9")]
    pub app: ::core::option::Option<super::shared::AppContext>,
}
#[derive(serde::Serialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WebrtcConnectResponse {
    #[prost(message, optional, tag = "1")]
    pub res: ::core::option::Option<super::gateway::ConnectResponse>,
}
#[derive(serde::Serialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WebrtcRemoteIceRequest {
    #[prost(string, tag = "1")]
    pub conn: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "2")]
    pub candidates: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(serde::Serialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct WebrtcRemoteIceResponse {
    #[prost(uint32, tag = "1")]
    pub added: u32,
}
#[derive(serde::Serialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WebrtcRestartIceRequest {
    #[prost(string, tag = "1")]
    pub conn: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub user_agent: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub ip: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "4")]
    pub req: ::core::option::Option<super::gateway::ConnectRequest>,
    #[prost(bool, tag = "5")]
    pub record: bool,
    #[prost(string, optional, tag = "8")]
    pub extra_data: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(message, optional, tag = "9")]
    pub app: ::core::option::Option<super::shared::AppContext>,
}
#[derive(serde::Serialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WebrtcRestartIceResponse {
    #[prost(message, optional, tag = "1")]
    pub res: ::core::option::Option<super::gateway::ConnectResponse>,
}
/// For RtpEngine
#[derive(serde::Serialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RtpEngineCreateOfferRequest {
    #[prost(uint64, tag = "1")]
    pub session_id: u64,
    #[prost(string, tag = "2")]
    pub room: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub peer: ::prost::alloc::string::String,
    #[prost(bool, tag = "5")]
    pub record: bool,
    #[prost(string, optional, tag = "6")]
    pub extra_data: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(message, optional, tag = "7")]
    pub app: ::core::option::Option<super::shared::AppContext>,
}
#[derive(serde::Serialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RtpEngineCreateOfferResponse {
    #[prost(string, tag = "1")]
    pub conn: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub sdp: ::prost::alloc::string::String,
}
#[derive(serde::Serialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RtpEngineSetAnswerRequest {
    #[prost(string, tag = "1")]
    pub conn: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub sdp: ::prost::alloc::string::String,
}
#[derive(serde::Serialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RtpEngineSetAnswerResponse {
    #[prost(string, tag = "1")]
    pub conn: ::prost::alloc::string::String,
}
#[derive(serde::Serialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RtpEngineCreateAnswerRequest {
    #[prost(uint64, tag = "1")]
    pub session_id: u64,
    #[prost(string, tag = "2")]
    pub room: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub peer: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub sdp: ::prost::alloc::string::String,
    #[prost(bool, tag = "5")]
    pub record: bool,
    #[prost(string, optional, tag = "6")]
    pub extra_data: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(message, optional, tag = "7")]
    pub app: ::core::option::Option<super::shared::AppContext>,
}
#[derive(serde::Serialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RtpEngineCreateAnswerResponse {
    #[prost(string, tag = "1")]
    pub conn: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub sdp: ::prost::alloc::string::String,
}
#[derive(serde::Serialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RtpEngineDeleteRequest {
    #[prost(string, tag = "1")]
    pub conn: ::prost::alloc::string::String,
}
#[derive(serde::Serialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RtpEngineDeleteResponse {
    #[prost(string, tag = "1")]
    pub conn: ::prost::alloc::string::String,
}
/// Generated client implementations.
pub mod media_edge_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct MediaEdgeClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl MediaEdgeClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> MediaEdgeClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> MediaEdgeClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            MediaEdgeClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn whip_connect(
            &mut self,
            request: impl tonic::IntoRequest<super::WhipConnectRequest>,
        ) -> std::result::Result<
            tonic::Response<super::WhipConnectResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cluster_media.MediaEdge/WhipConnect",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("cluster_media.MediaEdge", "WhipConnect"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn whip_remote_ice(
            &mut self,
            request: impl tonic::IntoRequest<super::WhipRemoteIceRequest>,
        ) -> std::result::Result<
            tonic::Response<super::WhipRemoteIceResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cluster_media.MediaEdge/WhipRemoteIce",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("cluster_media.MediaEdge", "WhipRemoteIce"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn whip_close(
            &mut self,
            request: impl tonic::IntoRequest<super::WhipCloseRequest>,
        ) -> std::result::Result<
            tonic::Response<super::WhipCloseResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cluster_media.MediaEdge/WhipClose",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("cluster_media.MediaEdge", "WhipClose"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn whep_connect(
            &mut self,
            request: impl tonic::IntoRequest<super::WhepConnectRequest>,
        ) -> std::result::Result<
            tonic::Response<super::WhepConnectResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cluster_media.MediaEdge/WhepConnect",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("cluster_media.MediaEdge", "WhepConnect"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn whep_remote_ice(
            &mut self,
            request: impl tonic::IntoRequest<super::WhepRemoteIceRequest>,
        ) -> std::result::Result<
            tonic::Response<super::WhepRemoteIceResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cluster_media.MediaEdge/WhepRemoteIce",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("cluster_media.MediaEdge", "WhepRemoteIce"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn whep_close(
            &mut self,
            request: impl tonic::IntoRequest<super::WhepCloseRequest>,
        ) -> std::result::Result<
            tonic::Response<super::WhepCloseResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cluster_media.MediaEdge/WhepClose",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("cluster_media.MediaEdge", "WhepClose"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn webrtc_connect(
            &mut self,
            request: impl tonic::IntoRequest<super::WebrtcConnectRequest>,
        ) -> std::result::Result<
            tonic::Response<super::WebrtcConnectResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cluster_media.MediaEdge/WebrtcConnect",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("cluster_media.MediaEdge", "WebrtcConnect"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn webrtc_remote_ice(
            &mut self,
            request: impl tonic::IntoRequest<super::WebrtcRemoteIceRequest>,
        ) -> std::result::Result<
            tonic::Response<super::WebrtcRemoteIceResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cluster_media.MediaEdge/WebrtcRemoteIce",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("cluster_media.MediaEdge", "WebrtcRemoteIce"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn webrtc_restart_ice(
            &mut self,
            request: impl tonic::IntoRequest<super::WebrtcRestartIceRequest>,
        ) -> std::result::Result<
            tonic::Response<super::WebrtcRestartIceResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cluster_media.MediaEdge/WebrtcRestartIce",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("cluster_media.MediaEdge", "WebrtcRestartIce"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn rtp_engine_create_offer(
            &mut self,
            request: impl tonic::IntoRequest<super::RtpEngineCreateOfferRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RtpEngineCreateOfferResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cluster_media.MediaEdge/RtpEngineCreateOffer",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("cluster_media.MediaEdge", "RtpEngineCreateOffer"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn rtp_engine_set_answer(
            &mut self,
            request: impl tonic::IntoRequest<super::RtpEngineSetAnswerRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RtpEngineSetAnswerResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cluster_media.MediaEdge/RtpEngineSetAnswer",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("cluster_media.MediaEdge", "RtpEngineSetAnswer"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn rtp_engine_create_answer(
            &mut self,
            request: impl tonic::IntoRequest<super::RtpEngineCreateAnswerRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RtpEngineCreateAnswerResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cluster_media.MediaEdge/RtpEngineCreateAnswer",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("cluster_media.MediaEdge", "RtpEngineCreateAnswer"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn rtp_engine_delete(
            &mut self,
            request: impl tonic::IntoRequest<super::RtpEngineDeleteRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RtpEngineDeleteResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cluster_media.MediaEdge/RtpEngineDelete",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("cluster_media.MediaEdge", "RtpEngineDelete"));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod media_edge_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with MediaEdgeServer.
    #[async_trait]
    pub trait MediaEdge: std::marker::Send + std::marker::Sync + 'static {
        async fn whip_connect(
            &self,
            request: tonic::Request<super::WhipConnectRequest>,
        ) -> std::result::Result<
            tonic::Response<super::WhipConnectResponse>,
            tonic::Status,
        >;
        async fn whip_remote_ice(
            &self,
            request: tonic::Request<super::WhipRemoteIceRequest>,
        ) -> std::result::Result<
            tonic::Response<super::WhipRemoteIceResponse>,
            tonic::Status,
        >;
        async fn whip_close(
            &self,
            request: tonic::Request<super::WhipCloseRequest>,
        ) -> std::result::Result<
            tonic::Response<super::WhipCloseResponse>,
            tonic::Status,
        >;
        async fn whep_connect(
            &self,
            request: tonic::Request<super::WhepConnectRequest>,
        ) -> std::result::Result<
            tonic::Response<super::WhepConnectResponse>,
            tonic::Status,
        >;
        async fn whep_remote_ice(
            &self,
            request: tonic::Request<super::WhepRemoteIceRequest>,
        ) -> std::result::Result<
            tonic::Response<super::WhepRemoteIceResponse>,
            tonic::Status,
        >;
        async fn whep_close(
            &self,
            request: tonic::Request<super::WhepCloseRequest>,
        ) -> std::result::Result<
            tonic::Response<super::WhepCloseResponse>,
            tonic::Status,
        >;
        async fn webrtc_connect(
            &self,
            request: tonic::Request<super::WebrtcConnectRequest>,
        ) -> std::result::Result<
            tonic::Response<super::WebrtcConnectResponse>,
            tonic::Status,
        >;
        async fn webrtc_remote_ice(
            &self,
            request: tonic::Request<super::WebrtcRemoteIceRequest>,
        ) -> std::result::Result<
            tonic::Response<super::WebrtcRemoteIceResponse>,
            tonic::Status,
        >;
        async fn webrtc_restart_ice(
            &self,
            request: tonic::Request<super::WebrtcRestartIceRequest>,
        ) -> std::result::Result<
            tonic::Response<super::WebrtcRestartIceResponse>,
            tonic::Status,
        >;
        async fn rtp_engine_create_offer(
            &self,
            request: tonic::Request<super::RtpEngineCreateOfferRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RtpEngineCreateOfferResponse>,
            tonic::Status,
        >;
        async fn rtp_engine_set_answer(
            &self,
            request: tonic::Request<super::RtpEngineSetAnswerRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RtpEngineSetAnswerResponse>,
            tonic::Status,
        >;
        async fn rtp_engine_create_answer(
            &self,
            request: tonic::Request<super::RtpEngineCreateAnswerRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RtpEngineCreateAnswerResponse>,
            tonic::Status,
        >;
        async fn rtp_engine_delete(
            &self,
            request: tonic::Request<super::RtpEngineDeleteRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RtpEngineDeleteResponse>,
            tonic::Status,
        >;
    }
    #[derive(Debug)]
    pub struct MediaEdgeServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> MediaEdgeServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for MediaEdgeServer<T>
    where
        T: MediaEdge,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/cluster_media.MediaEdge/WhipConnect" => {
                    #[allow(non_camel_case_types)]
                    struct WhipConnectSvc<T: MediaEdge>(pub Arc<T>);
                    impl<
                        T: MediaEdge,
                    > tonic::server::UnaryService<super::WhipConnectRequest>
                    for WhipConnectSvc<T> {
                        type Response = super::WhipConnectResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::WhipConnectRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MediaEdge>::whip_connect(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = WhipConnectSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/cluster_media.MediaEdge/WhipRemoteIce" => {
                    #[allow(non_camel_case_types)]
                    struct WhipRemoteIceSvc<T: MediaEdge>(pub Arc<T>);
                    impl<
                        T: MediaEdge,
                    > tonic::server::UnaryService<super::WhipRemoteIceRequest>
                    for WhipRemoteIceSvc<T> {
                        type Response = super::WhipRemoteIceResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::WhipRemoteIceRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MediaEdge>::whip_remote_ice(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = WhipRemoteIceSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/cluster_media.MediaEdge/WhipClose" => {
                    #[allow(non_camel_case_types)]
                    struct WhipCloseSvc<T: MediaEdge>(pub Arc<T>);
                    impl<
                        T: MediaEdge,
                    > tonic::server::UnaryService<super::WhipCloseRequest>
                    for WhipCloseSvc<T> {
                        type Response = super::WhipCloseResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::WhipCloseRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MediaEdge>::whip_close(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = WhipCloseSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/cluster_media.MediaEdge/WhepConnect" => {
                    #[allow(non_camel_case_types)]
                    struct WhepConnectSvc<T: MediaEdge>(pub Arc<T>);
                    impl<
                        T: MediaEdge,
                    > tonic::server::UnaryService<super::WhepConnectRequest>
                    for WhepConnectSvc<T> {
                        type Response = super::WhepConnectResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::WhepConnectRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MediaEdge>::whep_connect(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = WhepConnectSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/cluster_media.MediaEdge/WhepRemoteIce" => {
                    #[allow(non_camel_case_types)]
                    struct WhepRemoteIceSvc<T: MediaEdge>(pub Arc<T>);
                    impl<
                        T: MediaEdge,
                    > tonic::server::UnaryService<super::WhepRemoteIceRequest>
                    for WhepRemoteIceSvc<T> {
                        type Response = super::WhepRemoteIceResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::WhepRemoteIceRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MediaEdge>::whep_remote_ice(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = WhepRemoteIceSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/cluster_media.MediaEdge/WhepClose" => {
                    #[allow(non_camel_case_types)]
                    struct WhepCloseSvc<T: MediaEdge>(pub Arc<T>);
                    impl<
                        T: MediaEdge,
                    > tonic::server::UnaryService<super::WhepCloseRequest>
                    for WhepCloseSvc<T> {
                        type Response = super::WhepCloseResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::WhepCloseRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MediaEdge>::whep_close(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = WhepCloseSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/cluster_media.MediaEdge/WebrtcConnect" => {
                    #[allow(non_camel_case_types)]
                    struct WebrtcConnectSvc<T: MediaEdge>(pub Arc<T>);
                    impl<
                        T: MediaEdge,
                    > tonic::server::UnaryService<super::WebrtcConnectRequest>
                    for WebrtcConnectSvc<T> {
                        type Response = super::WebrtcConnectResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::WebrtcConnectRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MediaEdge>::webrtc_connect(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = WebrtcConnectSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/cluster_media.MediaEdge/WebrtcRemoteIce" => {
                    #[allow(non_camel_case_types)]
                    struct WebrtcRemoteIceSvc<T: MediaEdge>(pub Arc<T>);
                    impl<
                        T: MediaEdge,
                    > tonic::server::UnaryService<super::WebrtcRemoteIceRequest>
                    for WebrtcRemoteIceSvc<T> {
                        type Response = super::WebrtcRemoteIceResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::WebrtcRemoteIceRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MediaEdge>::webrtc_remote_ice(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = WebrtcRemoteIceSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/cluster_media.MediaEdge/WebrtcRestartIce" => {
                    #[allow(non_camel_case_types)]
                    struct WebrtcRestartIceSvc<T: MediaEdge>(pub Arc<T>);
                    impl<
                        T: MediaEdge,
                    > tonic::server::UnaryService<super::WebrtcRestartIceRequest>
                    for WebrtcRestartIceSvc<T> {
                        type Response = super::WebrtcRestartIceResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::WebrtcRestartIceRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MediaEdge>::webrtc_restart_ice(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = WebrtcRestartIceSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/cluster_media.MediaEdge/RtpEngineCreateOffer" => {
                    #[allow(non_camel_case_types)]
                    struct RtpEngineCreateOfferSvc<T: MediaEdge>(pub Arc<T>);
                    impl<
                        T: MediaEdge,
                    > tonic::server::UnaryService<super::RtpEngineCreateOfferRequest>
                    for RtpEngineCreateOfferSvc<T> {
                        type Response = super::RtpEngineCreateOfferResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::RtpEngineCreateOfferRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MediaEdge>::rtp_engine_create_offer(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = RtpEngineCreateOfferSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/cluster_media.MediaEdge/RtpEngineSetAnswer" => {
                    #[allow(non_camel_case_types)]
                    struct RtpEngineSetAnswerSvc<T: MediaEdge>(pub Arc<T>);
                    impl<
                        T: MediaEdge,
                    > tonic::server::UnaryService<super::RtpEngineSetAnswerRequest>
                    for RtpEngineSetAnswerSvc<T> {
                        type Response = super::RtpEngineSetAnswerResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::RtpEngineSetAnswerRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MediaEdge>::rtp_engine_set_answer(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = RtpEngineSetAnswerSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/cluster_media.MediaEdge/RtpEngineCreateAnswer" => {
                    #[allow(non_camel_case_types)]
                    struct RtpEngineCreateAnswerSvc<T: MediaEdge>(pub Arc<T>);
                    impl<
                        T: MediaEdge,
                    > tonic::server::UnaryService<super::RtpEngineCreateAnswerRequest>
                    for RtpEngineCreateAnswerSvc<T> {
                        type Response = super::RtpEngineCreateAnswerResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::RtpEngineCreateAnswerRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MediaEdge>::rtp_engine_create_answer(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = RtpEngineCreateAnswerSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/cluster_media.MediaEdge/RtpEngineDelete" => {
                    #[allow(non_camel_case_types)]
                    struct RtpEngineDeleteSvc<T: MediaEdge>(pub Arc<T>);
                    impl<
                        T: MediaEdge,
                    > tonic::server::UnaryService<super::RtpEngineDeleteRequest>
                    for RtpEngineDeleteSvc<T> {
                        type Response = super::RtpEngineDeleteResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::RtpEngineDeleteRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MediaEdge>::rtp_engine_delete(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = RtpEngineDeleteSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(empty_body());
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for MediaEdgeServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "cluster_media.MediaEdge";
    impl<T> tonic::server::NamedService for MediaEdgeServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
